"""empty message

Revision ID: 129be1a8b830
Revises: 7e0ad2dd208
Create Date: 2015-01-12 08:59:30.865071

"""

# revision identifiers, used by Alembic.
revision = '129be1a8b830'
down_revision = '7e0ad2dd208'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
