"""empty message

Revision ID: 7e0ad2dd208
Revises: 54d1a1d45135
Create Date: 2015-01-12 08:57:56.318418

"""

# revision identifiers, used by Alembic.
revision = '7e0ad2dd208'
down_revision = '54d1a1d45135'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
