#! /bin/bash

receivers=$1
admin_email_address="670271826@qq.com"

content=$2

# echo 'content' $content

#var=`echo $content|awk -F ',' '{print $2}'`
rvs=`echo $receivers | awk -F';' '{print $0}' | sed "s/;/ /g"`

for r in $rvs
do
	echo $content | mail -s 'Monitor trigger notifications' $r
done
echo $content | mail -s 'Monitor trigger notifications' $admin_email_address
