"""empty message

Revision ID: 1ca0370de9e1
Revises: 129be1a8b830
Create Date: 2015-01-12 09:00:46.070465

"""

# revision identifiers, used by Alembic.
revision = '1ca0370de9e1'
down_revision = '129be1a8b830'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
