"""empty message

Revision ID: 244c0f3c8d43
Revises: 1ca0370de9e1
Create Date: 2015-01-12 09:18:29.406672

"""

# revision identifiers, used by Alembic.
revision = '244c0f3c8d43'
down_revision = '1ca0370de9e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
