"""empty message

Revision ID: 3e7b8e2ea504
Revises: 3f0e4a21147a
Create Date: 2015-02-13 08:59:08.939522

"""

# revision identifiers, used by Alembic.
revision = '3e7b8e2ea504'
down_revision = '3f0e4a21147a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'action', 'trigger', ['trigger_id'], ['triggerid'])
    op.create_foreign_key(None, 'area_itemtype', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'area_itemtype', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'area_service', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'area_service', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'attr', 'operation', ['operation_id'], ['operationid'])
    op.create_foreign_key(None, 'attr', 'displaytablerow', ['displaytablerow_id'], ['displaytablerowid'])
    op.create_foreign_key(None, 'attr', 'chartconfig', ['chartconfig_id'], ['chartconfigid'])
    op.create_foreign_key(None, 'aws', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'chartconfig', 'window', ['window_id'], ['windowid'])
    op.create_foreign_key(None, 'displaytable', 'option', ['option_id'], ['optionid'])
    op.create_foreign_key(None, 'displaytablerow', 'displaytable', ['displaytable_id'], ['displaytableid'])
    op.create_foreign_key(None, 'email_receiver', 'emailschedule', ['email_id'], ['emailscheduleid'])
    op.create_foreign_key(None, 'email_receiver', 'receiver', ['receiver_id'], ['receiverid'])
    op.create_foreign_key(None, 'email_report', 'report', ['report_id'], ['reportid'])
    op.create_foreign_key(None, 'email_report', 'emailschedule', ['email_id'], ['emailscheduleid'])
    op.create_foreign_key(None, 'emailschedule', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'host', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'host', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'host_itemtype', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'host_itemtype', 'host', ['host_id'], ['hostid'])
    op.create_foreign_key(None, 'item', 'host', ['host_id'], ['hostid'])
    op.create_foreign_key(None, 'item', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'item', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'item', 'aws', ['aws_id'], ['awsid'])
    op.create_foreign_key(None, 'item', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'itemtype', 'normalitemtype', ['normalitemtype_id'], ['normalitemtypeid'])
    op.create_foreign_key(None, 'itemtype', 'aws', ['aws_id'], ['awsid'])
    op.create_foreign_key(None, 'itemtype', 'zbxitemtype', ['zbxitemtype_id'], ['zbxitemtypeid'])
    op.create_foreign_key(None, 'itemtype', 'itemdatatype', ['Itemdatatype_id'], ['itemdatatypeid'])
    op.create_foreign_key(None, 'operation', 'action', ['action_id'], ['actionid'])
    op.create_foreign_key(None, 'option', 'selectedmetrics', ['selectedmetrics_id'], ['selectedmetricsid'])
    op.create_foreign_key(None, 'page', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'reportimg', 'report', ['report_id'], ['reportid'])
    op.create_foreign_key(None, 'reportimg', 'emailschedule', ['emailschedule_id'], ['emailscheduleid'])
    op.create_foreign_key(None, 'selectedmetrics', 'report', ['report_id'], ['reportid'])
    op.create_foreign_key(None, 'selectedmetrics', 'window', ['window_id'], ['windowid'])
    op.create_foreign_key(None, 'service_itemtype', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'service_itemtype', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.add_column(u'trigger', sa.Column('comparetype', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'trigger', 'calculateditem', ['calculateditem_id'], ['calculateditemid'])
    op.create_foreign_key(None, 'window', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'window', 'page', ['page_id'], ['pageid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'window', type_='foreignkey')
    op.drop_constraint(None, 'window', type_='foreignkey')
    op.drop_constraint(None, 'trigger', type_='foreignkey')
    op.drop_column(u'trigger', 'comparetype')
    op.drop_constraint(None, 'service_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'service_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'selectedmetrics', type_='foreignkey')
    op.drop_constraint(None, 'selectedmetrics', type_='foreignkey')
    op.drop_constraint(None, 'reportimg', type_='foreignkey')
    op.drop_constraint(None, 'reportimg', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'host_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'host_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.drop_constraint(None, 'emailschedule', type_='foreignkey')
    op.drop_constraint(None, 'email_report', type_='foreignkey')
    op.drop_constraint(None, 'email_report', type_='foreignkey')
    op.drop_constraint(None, 'email_receiver', type_='foreignkey')
    op.drop_constraint(None, 'email_receiver', type_='foreignkey')
    op.drop_constraint(None, 'displaytablerow', type_='foreignkey')
    op.drop_constraint(None, 'displaytable', type_='foreignkey')
    op.drop_constraint(None, 'chartconfig', type_='foreignkey')
    op.drop_constraint(None, 'aws', type_='foreignkey')
    op.drop_constraint(None, 'attr', type_='foreignkey')
    op.drop_constraint(None, 'attr', type_='foreignkey')
    op.drop_constraint(None, 'attr', type_='foreignkey')
    op.drop_constraint(None, 'area_service', type_='foreignkey')
    op.drop_constraint(None, 'area_service', type_='foreignkey')
    op.drop_constraint(None, 'area_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'area_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'action', type_='foreignkey')
    ### end Alembic commands ###
