"""empty message

Revision ID: 3e9c39e7a487
Revises: 37d3b9a97e7c
Create Date: 2015-04-23 09:31:27.211311

"""

# revision identifiers, used by Alembic.
revision = '3e9c39e7a487'
down_revision = '37d3b9a97e7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedaccount',
    sa.Column('linkedaccountid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('linkedaccountname', sa.String(length=128), nullable=True),
    sa.Column('taxationaddress', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('linkedaccountid')
    )
    op.create_table('invoice',
    sa.Column('invoiceid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('invoiceid')
    )
    op.create_table('awsservice',
    sa.Column('awsserviceid', sa.BigInteger(), nullable=False),
    sa.Column('productcode', sa.String(length=128), nullable=True),
    sa.Column('productname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('awsserviceid')
    )
    op.create_table('apioperation',
    sa.Column('apioperationid', sa.BigInteger(), nullable=False),
    sa.Column('apioperationname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('apioperationid')
    )
    op.create_table('payeraccount',
    sa.Column('payeraccountid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('payeraccountname', sa.String(length=128), nullable=True),
    sa.Column('payerponumber', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('payeraccountid')
    )
    op.create_table('billingrow',
    sa.Column('billingrowid', sa.BigInteger(), nullable=False),
    sa.Column('billingperiodstartdate', sa.BigInteger(), nullable=True),
    sa.Column('billingperiodenddate', sa.BigInteger(), nullable=True),
    sa.Column('invoicedate', sa.BigInteger(), nullable=True),
    sa.Column('sellerofrecord', sa.String(length=128), nullable=True),
    sa.Column('usagetype', sa.String(length=128), nullable=True),
    sa.Column('rateid', sa.BigInteger(), nullable=True),
    sa.Column('itemdescription', sa.String(length=256), nullable=True),
    sa.Column('usagestartdate', sa.BigInteger(), nullable=True),
    sa.Column('usageenddate', sa.BigInteger(), nullable=True),
    sa.Column('usagequantity', sa.Float(), nullable=True),
    sa.Column('blendedrate', sa.Float(), nullable=True),
    sa.Column('currencycode', sa.String(length=64), nullable=True),
    sa.Column('costbeforetax', sa.Float(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('taxamount', sa.Float(), nullable=True),
    sa.Column('taxtype', sa.String(length=128), nullable=True),
    sa.Column('totalcost', sa.Float(), nullable=True),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('apioperation_id', sa.BigInteger(), nullable=True),
    sa.Column('payeraccount_id', sa.BigInteger(), nullable=True),
    sa.Column('linkedaccount_id', sa.BigInteger(), nullable=True),
    sa.Column('awsservice_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['apioperation_id'], ['apioperation.apioperationid'], ),
    sa.ForeignKeyConstraint(['awsservice_id'], ['awsservice.awsserviceid'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoiceid'], ),
    sa.ForeignKeyConstraint(['linkedaccount_id'], ['linkedaccount.linkedaccountid'], ),
    sa.ForeignKeyConstraint(['payeraccount_id'], ['payeraccount.payeraccountid'], ),
    sa.PrimaryKeyConstraint('billingrowid')
    )
    op.create_foreign_key(None, 'action', 'trigger', ['trigger_id'], ['triggerid'])
    op.create_foreign_key(None, 'area_itemtype', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'area_itemtype', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'area_service', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'area_service', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'attr', 'operation', ['operation_id'], ['operationid'])
    op.create_foreign_key(None, 'attr', 'displaytablerow', ['displaytablerow_id'], ['displaytablerowid'])
    op.create_foreign_key(None, 'attr', 'chartconfig', ['chartconfig_id'], ['chartconfigid'])
    op.create_foreign_key(None, 'aws', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'chartconfig', 'window', ['window_id'], ['windowid'])
    op.create_foreign_key(None, 'displaytable', 'option', ['option_id'], ['optionid'])
    op.create_foreign_key(None, 'displaytablerow', 'displaytable', ['displaytable_id'], ['displaytableid'])
    op.create_foreign_key(None, 'email_receiver', 'emailschedule', ['email_id'], ['emailscheduleid'])
    op.create_foreign_key(None, 'email_receiver', 'receiver', ['receiver_id'], ['receiverid'])
    op.create_foreign_key(None, 'email_report', 'report', ['report_id'], ['reportid'])
    op.create_foreign_key(None, 'email_report', 'emailschedule', ['email_id'], ['emailscheduleid'])
    op.create_foreign_key(None, 'emailschedule', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'host', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'host', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'host_itemtype', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'host_itemtype', 'host', ['host_id'], ['hostid'])
    op.create_foreign_key(None, 'item', 'host', ['host_id'], ['hostid'])
    op.create_foreign_key(None, 'item', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'item', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'item', 'aws', ['aws_id'], ['awsid'])
    op.create_foreign_key(None, 'item', 'area', ['area_id'], ['areaid'])
    op.create_foreign_key(None, 'itemtype', 'normalitemtype', ['normalitemtype_id'], ['normalitemtypeid'])
    op.create_foreign_key(None, 'itemtype', 'aws', ['aws_id'], ['awsid'])
    op.create_foreign_key(None, 'itemtype', 'zbxitemtype', ['zbxitemtype_id'], ['zbxitemtypeid'])
    op.create_foreign_key(None, 'itemtype', 'itemdatatype', ['Itemdatatype_id'], ['itemdatatypeid'])
    op.create_foreign_key(None, 'operation', 'action', ['action_id'], ['actionid'])
    op.create_foreign_key(None, 'option', 'selectedmetrics', ['selectedmetrics_id'], ['selectedmetricsid'])
    op.create_foreign_key(None, 'page', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'reportimg', 'report', ['report_id'], ['reportid'])
    op.create_foreign_key(None, 'reportimg', 'emailschedule', ['emailschedule_id'], ['emailscheduleid'])
    op.create_foreign_key(None, 'selectedmetrics', 'report', ['report_id'], ['reportid'])
    op.create_foreign_key(None, 'selectedmetrics', 'window', ['window_id'], ['windowid'])
    op.create_foreign_key(None, 'service_itemtype', 'service', ['service_id'], ['serviceid'])
    op.create_foreign_key(None, 'service_itemtype', 'itemtype', ['itemtype_id'], ['itemtypeid'])
    op.create_foreign_key(None, 'trigger', 'calculateditem', ['calculateditem_id'], ['calculateditemid'])
    op.create_foreign_key(None, 'window', 'user', ['user_id'], ['userid'])
    op.create_foreign_key(None, 'window', 'page', ['page_id'], ['pageid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'window', type_='foreignkey')
    op.drop_constraint(None, 'window', type_='foreignkey')
    op.drop_constraint(None, 'trigger', type_='foreignkey')
    op.drop_constraint(None, 'service_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'service_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'selectedmetrics', type_='foreignkey')
    op.drop_constraint(None, 'selectedmetrics', type_='foreignkey')
    op.drop_constraint(None, 'reportimg', type_='foreignkey')
    op.drop_constraint(None, 'reportimg', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'itemtype', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'host_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'host_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.drop_constraint(None, 'emailschedule', type_='foreignkey')
    op.drop_constraint(None, 'email_report', type_='foreignkey')
    op.drop_constraint(None, 'email_report', type_='foreignkey')
    op.drop_constraint(None, 'email_receiver', type_='foreignkey')
    op.drop_constraint(None, 'email_receiver', type_='foreignkey')
    op.drop_constraint(None, 'displaytablerow', type_='foreignkey')
    op.drop_constraint(None, 'displaytable', type_='foreignkey')
    op.drop_constraint(None, 'chartconfig', type_='foreignkey')
    op.drop_constraint(None, 'aws', type_='foreignkey')
    op.drop_constraint(None, 'attr', type_='foreignkey')
    op.drop_constraint(None, 'attr', type_='foreignkey')
    op.drop_constraint(None, 'attr', type_='foreignkey')
    op.drop_constraint(None, 'area_service', type_='foreignkey')
    op.drop_constraint(None, 'area_service', type_='foreignkey')
    op.drop_constraint(None, 'area_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'area_itemtype', type_='foreignkey')
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_table('billingrow')
    op.drop_table('payeraccount')
    op.drop_table('apioperation')
    op.drop_table('awsservice')
    op.drop_table('invoice')
    op.drop_table('linkedaccount')
    ### end Alembic commands ###
