"""empty message

Revision ID: 54d1a1d45135
Revises: None
Create Date: 2015-01-12 08:56:11.570018

"""

# revision identifiers, used by Alembic.
revision = '54d1a1d45135'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
